### ISSUE TITLE
Avoid rebuild in dev mode on unchanged local images?

### ISSUE THREAD

**Issue by brycewray** [11ty/eleventy-img#108] opened 2021-07-10 10:47 UTC
When in development mode (using Eleventy with the `--serve` flag) and with only local images, is there a flag (for either the Image plugin or Eleventy itself) that will tell the plugin **not** to rebuild all the images every time there's a change in the repo **other than** one of the images?

I have read the plugin documentation and every related article I can find, and have yet to see a mention of how to make Image rebuild only a changed local image in dev mode.

Thanks in advance for any guidance anyone can provide about this.

---

*Also asked in the Discussions section for Eleventy itself ([#1887](https://github.com/11ty/eleventy/discussions/1887)).*

**Comment by sachinsancheti1** [comment] 2021-07-11 03:58
hi bryncewray,

I could not figure out what to do here when I hit this road block a few months back. I decided to NOT PROCESS THE LOCAL IMAGES in DEV MODE. Instead, I set the production/build script to have a ELEVENTY_ENV=production


```js
if (process.env.ELEVENTY_ENV === 'production') {
// ...process some eleventy-img script...
}
```
my package.json file then uses the following scripts

```json
"scripts": {
  "dev": "eleventy --serve",
  "build": "ELEVENTY_ENV=production eleventy"
}
```

**Comment by brycewray** [comment] 2021-07-11 05:01
@sachinsancheti1 thanks. In my case, I do need to process them in dev mode, but yours is a good suggestion if that situation changes.

**Comment by Brixy** [comment] 2021-07-11 19:22
#51 seems to be related.

**Comment by zachleat** [comment] 2021-07-15 18:59
I posted a quick snippet that solves this on #51 https://github.com/11ty/eleventy-img/issues/51#issuecomment-880938400

**Comment by zachleat** [comment] 2021-07-15 20:56
https://www.11ty.dev/docs/plugins/image/#in-memory-cache-new-in-image-0.7.0 is what you need here!

**Comment by zachleat** [comment] 2021-07-15 20:57
You can use `DEBUG=EleventyImg` to check for cache hits and misses.

**Comment by zachleat** [comment] 2021-07-15 21:35
Per comment on Twitter I think this is a dupe of #51, let’s organize over there!

**Closed by zachleat** 2021-07-15 21:35 UTC
