### ISSUE TITLE
Feature request: Pre cache for faster builds?

### ISSUE THREAD

**Issue by bediu** [11ty/eleventy-img#130] opened 2021-10-11 09:47 UTC
I'm trying to run a seo friendly blog in 2021. We support webp avif and several versions of jpg. Our build times have started to suffer and take minutes - the thing is 99% of our images don't need to be re-built over and over again - specifically blog post headers and content.

My proposition is that given image x we should be also allowed to give a cache directory with pre-generated images so the plugin skips that image altogether and uses the content of the cache directory instead (no questions asked).

If the directory does not exist, or is empty, then the pre-cache is skipped and the images are rendered again.

Example: 
```javascript
let metadata = await Image(src, {
    widths: [600, 900, 1500],
    formats: ['webp', 'jpeg', 'avif'],
    urlPath: "/assets/img/blog/" + picture_id + "/",
    outputDir: "./dist/assets/img/blog/" + picture_id + "/",
    preCache: "/assets/img/blog/pre-cache/" + picture_id + "/", //       <- this
    filenameFormat: function (id, src, width, format, options) {
      const extension = path.extname(src)
      const name = path.basename(src, extension)
      return `${name}-${width}w.${format}`
    }
  })
```

It's not the end of the world for build times to last 2 minutes - but it's not fun because my homepage is growing and growing and a lot of time it's nice to just try and change things and the introduction of this plugin has made me avoid the codebase.

Thank you, eleventy rocks, all the best!

**Comment by zachleat** [comment] 2021-10-19 17:22
Duplicate of #116 

Thanks!

**Closed as completed by zachleat** 2021-10-19 17:22 UTC
Labels: duplicate
