### ISSUE TITLE
Possible to copy image (passthrough) rather than reprocess?

### ISSUE THREAD

**Issue by mbforbes** [11ty/eleventy-img#183] opened 2023-05-06 06:18 UTC
For outputting an image of the same format and size, is it possible to have eleventy-img simply copy the file rather than reprocess it?

I read through all the issues I could find that mentioned "copy" and "passthrough" but I couldn't find an answer. The closest I found was this [comment](https://github.com/11ty/eleventy-img/issues/133#issuecomment-974658201):

>> widths: [null] (default, keep original width)
>
> That should skip processing the images.

However, when I include `null` or `"auto"` in the widths, and I inspect those output files, they are different than the originals.

I ask because (a) I have thousands of photos, so this would help quicken deploys, and (b) I've done quite a bit of hand-optimizing exactly how the images are compressed, so I'd like to have them not re-run through a compression algorithm again.

Thank you!!

**Comment by elmuerte** [comment] 2023-05-19 09:16
I would also be nice if there was an option to include the original file (untouched) in the resulting image set.

So for example

```
Image("some-image.jps", {
  widths: [300],
  formats: ["jpeg"],
  includeOriginal: true
});
```

Would generate 1 image, and copy the original to the destination. The returned metadata would contain the information about both images.

**Comment by zachleat** [comment] 2024-12-13 23:23
I believe this is a duplicate of #133. But I’d also post another shout to passthrough copy, which does this!

We did some work to improve this with the imminently shipping v3.0.1 to improve passthrough copy for relative asset references: https://github.com/11ty/eleventy/pull/3573 The downside there is that we passthrough copy doesn’t add the width/height attributes.

Regardless, let’s group up at #133 and #212!

**Closed by zachleat** 2024-12-13 23:23 UTC
Labels: enhancement

**Comment by zachleat** [comment] 2026-07-25 01:51
Shipping with v7.0.0-alpha.5 more info at #212.
