### ISSUE TITLE
Build Fails on M1

### ISSUE THREAD

**Issue by manunamz** [11ty/eleventy-img#145] opened 2022-03-07 15:55 UTC
This is not so much an issue with `eleventy-img` so much as a note to others that this will fail due to a problem with one of its dependencies.

The [eleventastic](https://github.com/maxboeck/eleventastic) template (which uses `eleventy-img`) was failing for me with this output:

```bash
npm ERR! code 1
npm ERR! path /path/to/eleventastic/node_modules/sharp
npm ERR! command failed
npm ERR! command sh -c (node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)
npm ERR! CC(target) Release/obj.target/nothing/../node-addon-api/nothing.o
npm ERR!   LIBTOOL-STATIC Release/nothing.a
npm ERR!   TOUCH Release/obj.target/libvips-cpp.stamp
npm ERR!   CXX(target) Release/obj.target/sharp/src/common.o
npm ERR! info sharp Downloading https://github.com/lovell/sharp-libvips/releases/download/v8.10.5/libvips-8.10.5-darwin-arm64v8.tar.br
npm ERR! ERR! sharp Prebuilt libvips 8.10.5 binaries are not yet available for darwin-arm64v8
npm ERR! info sharp Attempting to build from source via node-gyp but this may fail due to the above error
npm ERR! info sharp Please see https://sharp.pixelplumbing.com/install for required dependencies
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@7.1.2
npm ERR! gyp info using node@16.9.1 | darwin | arm64
npm ERR! gyp info find Python using Python version 3.9.9 found at "/opt/homebrew/opt/python@3.9/bin/python3.9"
npm ERR! (node:69836) [DEP0150] DeprecationWarning: Setting process.config is deprecated. In the future the property will be read-only.
npm ERR! (Use `node --trace-deprecation ...` to show where the warning was created)
npm ERR! gyp info spawn /opt/homebrew/opt/python@3.9/bin/python3.9
...
```

The culprit seems to be [sharp](https://github.com/lovell/sharp):

```bash
sharp Prebuilt libvips 8.10.5 binaries are not yet available for darwin-arm64v8"
```

See (maybe?) [this issue](https://github.com/lovell/sharp/issues/3115)

**Comment by zachleat** [comment] 2022-03-07 17:45
Duplicate of #85 and #99, this fix shipped with 0.9.0 (latest version is 1.1.0). Eleventy Image will need to be upgraded to at least 0.9.0 on that starter.

**Closed by zachleat** 2022-03-07 17:45 UTC
Labels: duplicate
