### ISSUE TITLE
Copy className of img to a picture tag

### ISSUE THREAD

**Issue by hottabov** [11ty/eleventy-img#251] opened 2024-10-21 00:05 UTC
Please, make it possible to automatically asign the className of img to a generated picture tag. 

    "@11ty/eleventy": "^3.0.0"
    "@11ty/eleventy-img": "^5.0.0"

Thank you!

**Comment by zachleat** [comment] 2024-10-23 19:04
Duplicate of #243

**Closed by zachleat** 2024-10-23 19:04 UTC
Labels: duplicate
